%YAML:1.0
---
# === Camera intrinsics ===
Camera.fx: 440.5  
Camera.fy: 440.5 
Camera.cx: 320.0
Camera.cy: 205.5  

Camera.k1: 0.0
Camera.k2: 0.0
Camera.p1: 0.0
Camera.p2: 0.0

Camera.width: 640
Camera.height: 411 

# === Stereo baseline * fx ===
Camera.bf: 33.04  # 0.075 × 440.5

# === Stereo mode only ===
Camera.RGB: 1 # RGB

# === ORB extractor params ===
ORBextractor.nFeatures: 800
ORBextractor.scaleFactor: 1.2
ORBextractor.nLevels: 6
ORBextractor.iniThFAST: 20
ORBextractor.minThFAST: 7

# Window size settings
Viewer.ImageWidth: 426
Viewer.ImageHeight: 240

# === Optional ===
# dataset: "/home/jacob/slam_ws/ORB_SLAM2_clean/app"
