%YAML:1.0
---
# === Camera intrinsics ===
Camera.fx: 440.5  # Updated for 72° HFOV
Camera.fy: 440.5  # Updated for 72° HFOV
Camera.cx: 320.0
Camera.cy: 205.5   # Updated: 411/2

Camera.k1: 0.0
Camera.k2: 0.0
Camera.p1: 0.0
Camera.p2: 0.0

Camera.width: 640
Camera.height: 411  # Changed from 360

# === Stereo baseline * fx ===
Camera.bf: 33.04  # Updated: 0.075 × 440.5

# === Stereo mode only ===
Camera.RGB: 1 # 0: Grayscale, 1: RGB

# === ORB extractor params ===
ORBextractor.nFeatures: 1200
ORBextractor.scaleFactor: 1.2
ORBextractor.nLevels: 8
ORBextractor.iniThFAST: 20
ORBextractor.minThFAST: 7

# === Optional ===
# dataset: "/home/jacob/slam_ws/ORB_SLAM2_clean/app"
