%YAML:1.0
---
Camera.fx: 720.0
Camera.fy: 720.0
Camera.cx: 640.0
Camera.cy: 360.0
Camera.k1: 0.0
Camera.k2: 0.0
Camera.p1: 0.0
Camera.p2: 0.0
Camera.width: 1280
Camera.height: 720
Camera.bf: 376.0  # Can keep if needed for stereo SLAM

Camera.RGB: 1
Camera.Depth: 1
RGBD.ThDepth: 4.0  # Depth truncation at 4m (optional tweak later)

ORBextractor.nFeatures: 1200
ORBextractor.scaleFactor: 1.2
ORBextractor.nLevels: 8
ORBextractor.iniThFAST: 20
ORBextractor.minThFAST: 7

rgbd_dataset: /home/jacob/slam_ws/ORB_SLAM2_clean/app
