name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install base dependencies
        run: |
          pip install --upgrade pip setuptools wheel
          pip install numpy msgpack-rpc-python pytest
          pip install --no-build-isolation airsim
      - name: Install project requirements
        run: pip install -r requirements.txt
      - name: Install package
        run: pip install -e .
      - name: Run tests
        run: pytest -q
